name = "html-summarizer-agent"
main = ".mastra/output/index.js"
compatibility_date = "2024-08-01"

[env.production]
name = "html-summarizer-agent"

[vars]
DEEPSEEK_API_KEY = "sk-1edd0944d3d24a76b3ded1aa0298e20f"

# 如果需要绑定到自定义域名，取消注释下面的配置
# [[env.production.routes]]
# pattern = "your-domain.com/*"

# KV存储绑定（如果需要）
# [[kv_namespaces]]
# binding = "STORAGE"
# id = "your-kv-namespace-id"
